// FastJsonDL — basic usage example
//
// Demonstrates how to initialise the EPD panel, build a JSON layout, register
// custom fonts, and render everything using FastJsonDL.
//
// Target board : M5Paper S3 (ESP32-S3) — change BB_PANEL_M5PAPERS3 and the
//                font pointers to match your own hardware / font set.

#include <stdio.h>
#include "FastEPD.h"
#include "FastJsonDL.h"

// FONTS
#include "fast/ubuntu40.h"
// ---------------------------------------------------------------------------
// Example font stubs — replace with real font data generated by the
// FastEPD fontconvert tool (see FastEPD/fontconvert/README.md).
// ---------------------------------------------------------------------------
extern const uint8_t Ubuntu40[];   // declaration only; provide the definition
                                   // in a separate font source file.

// Font registry: maps JSON "font" field values to in-memory font data.
static const FastJsonDLFont fonts[] = {
    { "Ubuntu40", ubuntu40 },
};

// ---------------------------------------------------------------------------
// JSON layout
// ---------------------------------------------------------------------------
// ORDER matters: items are rendered top-to-bottom, just as they appear in the
// "items" array.  Drawing a black bar before the white text ensures the text
// is visible.
static const char LAYOUT_JSON[] = R"({
  "display_bpp": 1,
  "items": [
    {
      "type": "fillRect",
      "x": 0,
      "y": 0,
      "w": 540,
      "h": 60,
      "c": 0
    },
    {
      "type": "drawString",
      "font": "Ubuntu40",
      "string": "Hello from FastJsonDL!",
      "x": 10,
      "y": 10,
      "c": 1
    },
    {
      "type": "drawRect",
      "x": 10,
      "y": 80,
      "w": 300,
      "h": 120,
      "c": 0
    },
    {
      "type": "drawLine",
      "x1": 10,
      "y1": 220,
      "x2": 310,
      "y2": 220,
      "c": 0
    },
    {
      "type": "fillCircle",
      "x": 160,
      "y": 300,
      "r": 40,
      "c": 0
    }
  ]
})";

// ---------------------------------------------------------------------------
// app_main
// ---------------------------------------------------------------------------
extern "C" void app_main(void)
{
  printf("jsonDL drawing demo\n");
    static FASTEPD epd;

    // Initialise the panel.  Replace BB_PANEL_M5PAPERS3 with the constant
    // that matches your hardware (see the BB_PANEL_* enum in FastEPD.h).
    int rc = epd.initPanel(BB_PANEL_M5PAPERS3);
    if (rc != BBEP_SUCCESS) {
        printf("EPD init failed (%d)\n", rc);
        return;
    }

    // Build the renderer and register the font table.
    static FastJsonDL dl(epd);
    dl.setFontRegistry(fonts, sizeof(fonts) / sizeof(fonts[0]));

    // Render the JSON layout.
    if (!dl.renderJsonString(LAYOUT_JSON)) {
        printf("FastJsonDL error: %s\n", dl.getLastError());
        return;
    }

    // Push the frame buffer to the physical display.
    epd.fullUpdate();
}
